name: ci
on:
  push:
    branches:
      - master
jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - name: fetch head
        uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: cache .m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: create version number
        run: |
          echo $(date '+%Y%m%d').$(echo $GITHUB_SHA | cut -c1-7) > .version

      - name: set version
        run: ./mvnw versions:set -DnewVersion="$(cat .version)"

      - name: maven build
        run: ./mvnw -B install

      - name: store build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: target

      - name: maven deploy
        run: ./mvnw -B deploy
        env:
          GITHUB_TOKEN: ${{secrets.serverpass}}
